### ISSUE TITLE
Needs Error checking

### ISSUE THREAD

**Issue by achow101** [mostafab/neg5#15]
Manual entry of match data needs to have error checking. It needs the error checking that SQBS does to check the bonus points and check that the points per bonus for that match actually make sense (e.g. no negative bonuses). If there is a problem, it shouldn't save that match and instead warn the user there is an issue that needs to be fixed. Also, a field which is autofilled with the bonus points earned would also be useful for allowing users to error check themselves.

**Comment by jonahgreenthal** [comment]
Subset of #24, other than the feature request in the last sentence.
