### ISSUE TITLE
Total Scores are displayed as floats

### ISSUE THREAD

**Issue by jwesly** [mostafab/neg5#25]
I'm guessing that someone forgot to just cast it to the closest integer.

![image](https://cloud.githubusercontent.com/assets/6673175/13726256/2ddca188-e88d-11e5-89f0-345c622b00c4.png)

**Comment by jonahgreenthal** [comment]
I don't know much about JavaScript's type system other than that it's
nearly nonexistent, but how are floating-point errors even accumulating
here?

**Comment by jwesly** [comment]
javascript is weird. easy fix is to just round to nearest decimal

**Comment by jonahgreenthal** [comment]
Mostafa can do what he wants, but I would be very hesitant to choose an
easy fix that might be papering over a more serious issue.

**Comment by jwesly** [comment]
it seems that the accepted solution is to just round when displaying http://stackoverflow.com/questions/1458633/how-to-deal-with-floating-point-number-precision-in-javascript

**Comment by jonahgreenthal** [comment]
That describes a situation in which it is understood why floating point
error would accumulate. In this one I see no such reason, since integers
can be represented exactly in fp.

**Comment by alopezlago** [comment]
In team.js parseFloat is used in a lot of methods like getTossupTotals.
Does neg5 support non-integer point values? If not, we should be using
parseInt instead. That might be a reason we're seeing this.

On Sat, Mar 12, 2016 at 5:11 PM, Jonah Greenthal <notifications@github.com>
wrote:

> That describes a situation in which it is understood why floating point
> error would accumulate. In this one I see no such reason, since integers
> can be represented exactly in fp.
>
> On Saturday, March 12, 2016, Jabez Wesly <notifications@github.com> wrote:
>
> > it seems that the accepted solution is to just round when displaying
> >
> http://stackoverflow.com/questions/1458633/how-to-deal-with-floating-point-number-precision-in-javascript
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/mostafab/neg5/issues/25#issuecomment-195846347>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mostafab/neg5/issues/25#issuecomment-195846543>.
>



-- 
-Alejandro

**Comment by jonahgreenthal** [comment]
If it does, IMO it shouldn't (because the costs outweigh the benefits and the whole thing is kind of silly). If your format requires rational non-integer point values, multiply everything by the least common denominator; if your format requires irrational point values, stop that.

**Comment by jonahgreenthal** [comment]
I am told that this bug occurs with other numbers besides total scores (in particular, games played; not sure on what display).

**Comment by mostafab** [comment]
Fixed when changed from Mongo to Postgres. Have not seen this issue come up since.
