### ISSUE TITLE
How to run this locally?

### ISSUE THREAD

**Issue by epicfaace** [mostafab/neg5#4]
I have already downloaded node.js and MongoDB. I tried to do "npm install" and here is what it gave me on the command line:

npm install
npm WARN package.json neg_five@1.0.0 No repository field.
npm WARN package.json passport@0.3.2 No README data
npm WARN package.json short-mongo-id@0.1.1 No repository field.

**Comment by mostafab** [comment]
Those warnings aren't that big of a deal. You can start the node server by either running "npm start" or "node server.js". You'll also have to have your mongo instance running as well to store data. To start a mongodb instance, create a "data" folder somewhere, cd to wherever mongo is installed (for me it was "C:/Program Files/MongoDB/Server/3..0/bin") and run the command : "mongod --dbpath /path/to/your data/folder". any information you save now will be stored at that folder location. 

There's lots of good information here:
https://docs.mongodb.org/manual/tutorial/

**Comment by epicfaace** [comment]
This is what I get when I try "npm start":

npm start

> neg_five@1.0.0 start /Users/asharv/git/neg5
> node server.js


/Users/asharv/git/neg5/app/routes/stats-route.js:152
tournamentName : tournamentName, roundsInfo : roundsInfo, roundsInfo, linkName
                                                                    ^
SyntaxError: Unexpected token ,
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at module.exports (/Users/asharv/git/neg5/config/express.js:39:5)
    at Object.<anonymous> (/Users/asharv/git/neg5/server.js:9:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

npm ERR! neg_five@1.0.0 start: `node server.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the neg_five@1.0.0 start script.
npm ERR! This is most likely a problem with the neg_five package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls neg_five
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 13.4.0
npm ERR! command "node" "/usr/local/bin/npm" "start"
npm ERR! cwd /Users/asharv/git/neg5
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/asharv/git/neg5/npm-debug.log
npm ERR! not ok code 0


And when I look in the log:
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@1.4.28
3 info using node@v0.10.33
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart neg_five@1.0.0
6 info start neg_five@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info neg_five@1.0.0 Failed to exec start script
9 error neg_five@1.0.0 start: `node server.js`
9 error Exit status 8
10 error Failed at the neg_five@1.0.0 start script.
10 error This is most likely a problem with the neg_five package,
10 error not with npm itself.
10 error Tell the author that this fails on your system:
10 error     node server.js
10 error You can get their info via:
10 error     npm owner ls neg_five
10 error There is likely additional logging output above.
11 error System Darwin 13.4.0
12 error command "node" "/usr/local/bin/npm" "start"
13 error cwd /Users/asharv/git/neg5
14 error node -v v0.10.33
15 error npm -v 1.4.28
16 error code ELIFECYCLE
17 verbose exit [ 1, true ]```

**Comment by mostafab** [comment]
Hmm, that's odd. I just tried cloning and it starts fine after I do "npm install". 
Can you pull the latest changes and try ```npm -g install npm``` to update to the latest version of npm and try again?

I also just noticed the first error is being caused by a typo, which I've now fixed. Can you try it again with the latest push?

**Comment by epicfaace** [comment]
Thanks, it works now.
