### ISSUE TITLE
Warn on total scores not divisible by 5

### ISSUE THREAD

**Issue by jonahgreenthal** [mostafab/neg5#70]

**Comment by rjaguar3** [comment]
This should produce an error if the format doesn't allow for non-multiple-of-5 scores, see #24.

**Comment by mostafab** [comment]
I believe the general case for this would be to warn/output error if ```score % greatest_common_divisor(all_scores) != 0```?

**Comment by jonahgreenthal** [comment]
Where does `all_scores` come from? But yes, assuming it is properly defined.

**Comment by mostafab** [comment]
Sorry, I meant the tossup values. So if you had something like [10, 20, -5] as your tossup values, the gcd would be 5 and all scores should be divisible by 5.

**Comment by jonahgreenthal** [comment]
That's not correct; bonus scores could contribute too.

**Comment by mostafab** [comment]
So the gcd of the tossup values and the value of a bonus part?

**Comment by jonahgreenthal** [comment]
That only works if all bonus parts have the same value, which is not necessarily true. I'd just do `gcd(all tossup values, bonus GCD)` where `bonus GCD` is entered manually.

**Comment by mostafab** [comment]
Currently, the application assumes each bonus part is worth the same, so the above would work. If at a later time I go back and add in support for bonus parts potentially being worth variable amounts, I'd have to change it to your solution.

**Comment by jonahgreenthal** [comment]
That's inconsistent with ACF rules, so I suggest changing it sooner rather than later :-)

**Comment by mostafab** [comment]
Would it really be that high of a priority, though? [According to the ACF rules I found](https://acf-quizbowl.com/official-gameplay-rules/#h.8bwh50kvbpas), "in virtually all cases, a bonus will consist of three parts worth 10 points each".

**Comment by jonahgreenthal** [comment]
I can't tell you how to prioritize your project, but it is still possible for bonus parts to have different values in ACF-rules quizbowl. The most common case would be a part that asks for two answers worth 5 points each.

**Comment by mostafab** [comment]
I don't think it would be hard to add in, but I'm wondering if the other issues should take precedence.

**Comment by mostafab** [comment]
Warning added in commit ```9b6f4a2dbd29fc26367b5c06e33547ff41beeb03```
